import { GoogleGenerativeAI } from '@google/generative-ai'

export async function generateEmbedding(text: string) {
  if (!process.env.GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY is missing from environment variables.")
  }

  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY)
  const model = genAI.getGenerativeModel({ model: 'gemini-embedding-001' })

  // Force outputDimensionality down to 768 to comfortably fit inside the Supabase column limits structure generated by nomic earlier
  const result = await model.embedContent({
    content: { role: "user", parts: [{ text: text }] },
    outputDimensionality: 768
  } as any)

  return result.embedding.values
}
